### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [eylles/adw-gtk2-colorizer#2]
Hey there, came there because I was, too, completely annoyed by the last remains of gtk2 in my GIMP and other legacy apps and wanted to theme that too.
Your repo was listed on the adw-gtk3 project README.md, so I tried it out.
But, I ain't so sure how to try it.
I've assumed I needed to install the theme first, to my adw-gtk3 folder (/usr/share/themes so make install did the trick in the adw-gtk2)
and then, make use of the python script to recolor it using the color profile from gradience 
`python3 colorize.py -f /home/pm/.var/app/com.github.GradienceTeam.Gradience/config/presets/official/catppuccin-frappe.json -r /home/pm/Documents/adw-gtk2-colorizer/`
but it doesn't make any real changes at all. Does it need extra rights to edit the theme, or does it just set the gtk2rc config file locally? Ain't really sure.

**Comment by eylles** [comment]
well that's on me, i wasn't really expecting anyone to use this at all cuz who would want to theme something old and as good as deprecated as gtk2...

so anyway, the problem is that in the python script i more or less harcoded it to assume that the gtk2 theme is installed to `~/.local/share/themes/`... 

give me a moment and i will push a commit to pass a new flag `-t` to specify the output directory.
